# Generated by Django 3.2.7 on 2021-09-17 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Terminado', 'Terminado'), ('Suspendido', 'Suspendido')], default='Pendiente', max_length=25)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_ini_estimada', models.DateField(verbose_name='Fecha de Inicio Estimada')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha de Fin Estimada')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rol.rol')),
            ],
        ),
    ]
