# Generated by Django 3.2.6 on 2021-10-07 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userstory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sprint', '0001_initial'),
        ('tipoUserStory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0001_initial'),
        ('flujo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_fase', models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Control de Calidad', 'Control de Calidad')], default='To Do', max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del User Story')),
                ('duracion_estimada', models.TimeField()),
                ('duracion_restante', models.IntegerField(blank=True, null=True)),
                ('valor_negocio', models.PositiveIntegerField(validators=[userstory.models.rango])),
                ('prioridad', models.PositiveIntegerField(validators=[userstory.models.rango])),
                ('valor_tecnico', models.PositiveIntegerField(validators=[userstory.models.rango])),
                ('estado', models.PositiveIntegerField(choices=[(2, 'Pendiente'), (1, 'Asignado'), (0, 'Finalizado')], default=2)),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flujo.fase')),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flujo.flujo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint.sprint')),
                ('sprints_asignados', models.ManyToManyField(blank=True, related_name='userstory_sprint_asignado', to='sprint.Sprint')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_us', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoUserStory.tipouserstory')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstimaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_estimada', models.PositiveIntegerField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_fase', models.CharField(blank=True, choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Control de Calidad', 'Control de Calidad')], max_length=30, null=True)),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flujo.fase')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to='')),
                ('binario', models.BinaryField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('estado_fase', models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Control de Calidad', 'Control de Calidad')], default='To Do', max_length=30)),
                ('fase_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flujo.fase')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint')),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
