# Generated by Django 3.2.7 on 2021-09-17 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoUserStory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userstory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstory',
            name='tipo_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipoUserStory.tipouserstory'),
        ),
        migrations.AddField(
            model_name='nota',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory'),
        ),
        migrations.AddField(
            model_name='nota',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userstory.userstory'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
